<a href="https://colab.research.google.com/github/Vokturz/Curso-Python-BCCh/blob/main/clase3/Clase3_Intro_librerias_y_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librerías

Una librería es un conjunto de funciones, clases y módulos que alguien ha escrito y que están disponibles para que otros las utilicen en sus programas. El gran beneficio de ellas es que permiten reutilizar código, accediendo por ejemplo a funciones muy complejas de programar (para qué reinventar la rueda, ¿no?).

## Cómo utilizar una librería

Para usar una librería primero debemos asegurarnos de que esta está instalada. Existen varias formas de instalar una librería, siendo la más común el usar el gestor de paquetes de Python `pip` dentro de una consola con la sintaxis `pip install nombre_libreria`.

Una vez instalada, dentro del código de Python debemos importarla:

```python
import nombre_libreria # importar directamente
import nombre_libreria as alias # usar un alias
from nombre_libreria import una_funcion # importar algo particular
```

A continuación importaremos y mostraremos ciertas utilidades que existen por defecto en Python

In [ ]:
# Funciones matemáticas
import math
print(math.sqrt(16)) # Raiz cuadrada

4.0


In [ ]:
# Trabajar con fechas y horas
from datetime import datetime
now = datetime.now()
print(now) # La hora en Colab está en UTC+0

2023-10-17 03:23:45.391136


In [ ]:
# Generador de números aleatorios
import random
for i in range(5):
  print(random.randint(1,10)) # Número entero aleatorio entre 1 y 10

6
9
4
2
6


In [ ]:
# Hacer peticiones HTTP, como descargar una página web
# Esto es importante por ejemplo, para hacer scraping
import requests
response = requests.get('https://www.udd.cl/')

# Mostramos solo los primeros 2000 caracteres
print(response.text[:2000])

<!DOCTYPE html>
<html lang="es-ES">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta name="theme-color" content="#014c8f">
	<!-- Google Tag Manager -->
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','GTM-5VPXPW');</script>
	<!-- End Google Tag Manager -->
	<!-- Webtracking -->
	<script type="text/javascript">
		var _paq = _paq || [];
		_paq.push(['trackPageView']);
		_paq.push(['enableLinkTracking']);
		(function() {
		var u="https://wtcl1.fidelizador.com/track.php?slug=udd";
		_paq.push(['setTrackerUrl', u]);
		_paq.push(['setSiteId', '1']);
		var d=document,
			g=d.createElement('sc

# NumPy

NumPy es una librería especializada en operaciones matemáticas y manipulación de vectores y matrices. Incluye un montón de funciones matemáticas, así como una estructura de datos propia llamada `ndarray` que es mucho más rapida que las listas convencionales de Python y que ademas aporta una mayor versatilidad al permitir describir matrices.




In [4]:
import numpy as np # Comunmente se importa con el alias np

# Creamos un array a partir de una lista
un_array = np.array([1,2,3])
type(un_array)

numpy.ndarray

Existen diferencias importantes a la hora de trabajar con un array versus trabajar con un lista:

- Un array permite operaciones elemento a elemento sin tener que utilizar un bucle para iterar sobre ellos. Esto le agrega simpleza y eficiencia a la programación.
- Un array es de tamaño fijo, es decir, no se puede cambiar su tamaño una vez creado. No funcionan `array.append`, `array.remove`, ni `del array[i]`, mientras que para una lista si se tienen estas funcionalidades.
- Es altamente recomendado que un array sea creado con elementos del mismo tipo

In [5]:
del un_array[0] # Esto lanzará un error

ValueError: ignored

In [ ]:
# Creamos un array de 3x3
una_matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(una_matriz)
print("Dimension de la matriz:", una_matriz.shape) # 3 x 3
print("Total filas:", len(una_matriz))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension de la matriz: (3, 3)
Total filas: 3


A continuación se muestran algunas operaciones sobre arrays

In [7]:
# Sumar arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2) # Suma elemento a elemento

[5 7 9]


In [8]:
# Summar un número a un array:
print(arr1 + 10)

[11 12 13]


In [ ]:
# Concatenar arrays
arr_concatenado = np.concatenate([arr1, arr2])
print(arr_concatenado)

[1 2 3 4 5 6]


In [ ]:
un_array = np.arange(11) # similar a list(range(11))
print("Array original:",un_array)

# Funciones aritmeticas sobre un array
print("   Elevado a 2:", np.power(un_array, 2))
print("      Promedio:", np.mean(un_array))
print("       Mediana:", np.median(un_array))
print("        Máximo:", np.max(un_array))
print("        Mínimo:", np.min(un_array))


Array original: [ 0  1  2  3  4  5  6  7  8  9 10]
   Elevado a 2: [  0   1   4   9  16  25  36  49  64  81 100]
      Promedio: 5.0
       Mediana: 5.0
        Máximo: 10
        Mínimo: 0


In [ ]:
una_matriz = np.array([[1, 2], [3, 4], [5, 6]])
print(una_matriz)
print('---')
print("Reshape (2,3)") # Modificar la forma de un array
print(una_matriz.reshape(2, 3))
print('---')
print("Matriz traspuesta")
print(una_matriz.T)

[[1 2]
 [3 4]
 [5 6]]
---
Reshape (2,3)
[[1 2 3]
 [4 5 6]]
---
Matriz traspuesta
[[1 3 5]
 [2 4 6]]


En NumPy existen muchas más funciones, las cuales están muy bien documentadas en su [página web](https://numpy.org/doc/stable/reference/routines.html). Algunas de ellas que no han sido ejemplificadas aquí son:

1. Creación de Arrays
  - `np.zeros(shape)`: Crea un array de dimension `shape` lleno de ceros
  - `np.ones(shape)`: Crea un array de dimension `shape` lleno de unos
  - `np.linspace(ini, fin, total)`: Crea un array de `total` números entre `ini` y `fin`
2. Más funciones estadísticas
  - `np.std(arr)`: Calcula la desviación estándar de un array
  - `np.argmin(arr)`: Encuentra el *índice* del valor mínimo en el array
  - `np.argmax(arr)`: Encuentra el *índice* del valor máximo en el array
  - `np.percentile(arr, q)`: Calcula el q-ésimo percentil del array
3. Operaciones de álgebra lineal
  - `np.dot(A, B)`: Producto punto de dos arrays
  - `np.cross(A, B)`: Producto cruz de dos arrays
  - `np.linalg.inv(matriz)`: Calcula la inversa de una matriz
4. Funciones Trigonométricas (Array debe estar en radianes)
  - `np.sin(arr)`: Calcula el seno de cada elemento del array
  - `np.cos(arr)`: Calcula el coseno de cada elemento del array
  - `np.tan(arr)`: Calcula la tangente de cada elemento del array
  
  Para ir familiarizandonos, volvamos a resolver los ejercicios de la clase anterior, pero esta vez usando NumPy:

  1. Dado un diccionario de indicadores mensuales, defina
 - Una función que calcule la media de un indicador dada una clave
 - Una función que, dado un indicador, retorne el mes más bajo. Asuma que la lista de cada indicador está ordenada de Enero a Junio


In [ ]:
# Los indicadores estan ordenados de Enero a Junio
indicadores_mensuales = {
      "IPC": [0.8, -0.1, 1.1, 0.3, 0.1, -0.2],
      "Tasa de Desempleo": [8.04, 8.37, 8.81, 8.66, 8.52, 8.53],
      "Imacec": [0.2, -0,5, -2.1, -0.9, -0.8]
  }

indice_meses = {0: "Enero",
                1: "Febrero",
                2: "Marzo",
                3: "Abril",
                4: "Mayo",
                5: "Junio"}

def calcular_media(indicadores, clave):
  """Calcula la media de un indicador"""
  media = 0 # Reemplazar!
  return round(media, 2)


def mes_minimo(indicadores, clave, indice_meses):
  """Retorna el mes donde el indicador fue mínimo"""
  indice_mes_minimo = 0 # Reemplazar
  return indice_meses[indice_mes_minimo]

assert calcular_media(indicadores_mensuales, "IPC") == 0.33, "Media IPC incorrecta"
assert mes_minimo(indicadores_mensuales, "Imacec", indice_meses) == "Marzo", "Incorrecto"


AssertionError: ignored

2. Calcule la variación porcentual de una lista de intereses anuales. La fórmula de la variación porcentual es

$\Large\Delta \%_\text{actual} = \frac{\text{periodo actual} - \text{periodo anterior}}{\text{periodo anterior}} \times 100 $


In [ ]:
# Tasas de interes anuales
tasas_interes = [2.5, 2.6, 2.7, 2.5, 2.8, 2.9]

def calcular_variacion(tasas):
  """Calcula la variacion porcentual de un año a otro en las tasas"""
  tasas_np = np.array(tasas)
  variaciones = np.array([]) # Reemplazar
  return variaciones.round(2)

# Si todo está en orden no debería aparecer un error
assert calcular_variacion(tasas_interes) == [4, 3.8, -7.4, 12, 3.6], "Incorrecto"

<ipython-input-66-a46889cb9562>:11: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  assert calcular_variacion(tasas_interes) == [4, 3.8, -7.4, 12, 3.6], "Incorrecto"


AssertionError: ignored

NumPy es la base para otras librerías muy utilizadas en el área de datos:
- [SciPy](https://scipy.org/) es una librería que extiende las capacidades de NumPy añadiendo algoritmos de álgebra lineal, optimización, procesamiento de señales, distribuciones estadísticas, entre otros.
- [Scikit-learn](https://scikit-learn.org/) es una de las librerías más populares para Machine Learning en Python.
- [**Pandas**](https://pandas.pydata.org/) es una de las herramientas fundamentales para la manipulación y el análisis de datos en Python. Tiene las estructuras de datos `Dataframe` y `Series` optimizadas para análisis de datos tabulares.

Existen muchas más librerías basadas en NumPy, por ejemplo, en astronomía la librería AstroPy es muy conocida. En el campo del aprendizaje profundo (deep learning), frameworks como Tensorflow y PyTorch están muy influenciados por NumPy. En el mismo campo, Google liberó hace menos de dos años un framework llamado JAX, el cual utiliza la misma sintaxis de NumPy.


## Enlaces externos
- [W3Schools](https://www.w3schools.com/python/numpy/default.asp) tiene tutoriales simples de NumPy
- La página oficial de NumPy tiene una [guía básica](https://numpy.org/doc/stable/user/absolute_beginners.html) de uso